### ISSUE TITLE
Please provide exported metrics details

### ISSUE THREAD

**Issue by arkady-emelyanov** [spaghettifunk/druid-prometheus-exporter#1]
Otherwise, it would be hard to setup proper Grafana dashboard.

**Comment by spaghettifunk** [comment]
Working on it 😃 I let you know when it's ready

**Comment by spaghettifunk** [comment]
I added a bunch of metrics as described in [here](https://druid.apache.org/docs/latest/operations/metrics.html). If you need extra metrics, open a new issue with what you need :)
